1. What is Numpy
NumPy, which stands for "Numerical Python," is a popular Python library for numerical and scientific computing. It provides support for working with large, multi-dimensional arrays and matrices of data, along with a collection of mathematical functions to operate on these arrays.
NumPy is a fundamental library for data manipulation and analysis in Python and is widely used in various fields such as data science, machine learning, scientific research, and engineering.
Here are some key features and aspects of NumPy:
* Multi-dimensional Arrays: NumPy's core data structure is the ndarray (short for n-dimensional array). It allows you to create arrays of various dimensions, including 1D, 2D, and higher-dimensional arrays. I
* Efficient and Fast: NumPy is implemented in C and optimized for performance, making it much faster than standard Python lists when performing array operations. This efficiency is crucial for handling large datasets and complex mathematical computations.


In [2]:
import numpy as np
a=np.array([34])
b=np.array([10,30,25,43,21])
c=np.array([[10,30,25,43,21],[10,30,25,43,21]])
d=np.array([[10,30,25,43,21],[10,30,25,43,21],[10,30,25,43,21]])

print(a)
print(b)
print(c)
print(d)

[34]
[10 30 25 43 21]
[[10 30 25 43 21]
 [10 30 25 43 21]]
[[10 30 25 43 21]
 [10 30 25 43 21]
 [10 30 25 43 21]]


In [3]:
import numpy as np
a=np.array(34)
b=np.array([10,30,25,43,21])
c=np.array([[10,30,25,43,21],[10,30,25,43,21]])
d = np.array([[10, 30, 25, 43, 21], [10, 30, 25, 43, 21], [10, 30, 25, 43, 21]])
print(a)
print(b)
print(c)
print(d)
print()
print("a:",a.ndim)
print("b:",b.ndim)
print("c:",c.ndim)
print("d:",d.ndim)




34
[10 30 25 43 21]
[[10 30 25 43 21]
 [10 30 25 43 21]]
[[10 30 25 43 21]
 [10 30 25 43 21]
 [10 30 25 43 21]]

a: 0
b: 1
c: 2
d: 2


1. d array - vector
2. d array - matrix
3. d array - tensor

In [4]:
# index 
arr = np.array ([20,22,23,2,2])
print(arr[3])

2


In [5]:
# sciling
arr = np.array ([20,22,23,25,2])
print(arr[0:5:2])

[20 23  2]


### numpy
string
integer
float
boolean

view~the view own the data and any change made to the view will affect the original array and any chnages made to the original array will be effect
copy ~ is used copy the array

In [6]:
arr = np.array ([20,22,23,25,2])
sarr=arr[1:5]
print(arr)
print(sarr)
sarr[2]=100
print(arr)
print(sarr)

[20 22 23 25  2]
[22 23 25  2]
[ 20  22  23 100   2]
[ 22  23 100   2]


In [7]:
#copy()
arr=np.array([1,2,3,4,5])
arr2=arr.copy()
arr[0]=42
print(arr)
print(arr2)


[42  2  3  4  5]
[1 2 3 4 5]


In [8]:
#view()
arr=np.array([1,2,3,4,5])
arr2=arr.view()
arr[0]=42
print(arr)
print(arr2)

[42  2  3  4  5]
[42  2  3  4  5]


# zeros

In [9]:
a=np.zeros((6,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
a=np.zeros((6,), dtype=int)
print(a)

[0 0 0 0 0 0]


In [11]:
a=np.zeros(6)
print(a)

[0. 0. 0. 0. 0. 0.]


### ones()

In [12]:
a=np.ones((6,2))*5
print(a)

[[5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]]


In [13]:
#eye
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
arr=np.diag((3,4,1,6))
print(arr)
print(arr.ndim)
print(arr.shape)

[[3 0 0 0]
 [0 4 0 0]
 [0 0 1 0]
 [0 0 0 6]]
2
(4, 4)


In [15]:
arr=np.array([[10,30,25,43,21],[10,30,25,43,21],[1,2,3,4,5]])
print(np.diag(arr))
print()
print(np.diag((3,9,5)))

[10 30  3]

[[3 0 0]
 [0 9 0]
 [0 0 5]]


In [16]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


### randint()

In [19]:
rand=np.random.randint(0,10,2)
print(rand)

[5 3]


In [20]:
rand=np.random.rand(0,10)
print(rand)

[]


In [22]:
rand=np.random.rand(10)
print(rand)

[0.87611721 0.07934329 0.83246587 0.4498222  0.20573318 0.50293861
 0.43783954 0.04467201 0.03626331 0.59746883]


## reshape( )

In [25]:
arr=np.array([1,2,3,4,5,50])
print(arr)
arr2=arr.reshape(3,3)
print(arr2)

[ 1  2  3  4  5 50]


ValueError: cannot reshape array of size 6 into shape (3,3)

In [37]:
arr=np.array([1,2,3,4,5,6])
print(type(arr))
arr2=arr.reshape(3,2)
print(arr2)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]


In [28]:
arr=np.random.randint(0,100,12)
print(arr)
print()
arr=arr.reshape(4,3)
print(arr)
print("array value is :",arr[0][1])
print("array value is :",arr[1][0])
print(arr.shape)
print()
arr=arr.reshape(-1,4)
print(arr)
print()
arr=arr.reshape(2,-1)
print(arr)


[73 72 39 78 77 91 38 57 76 68 40 29]

[[73 72 39]
 [78 77 91]
 [38 57 76]
 [68 40 29]]
array value is : 72
array value is : 78
(4, 3)

[[73 72 39 78]
 [77 91 38 57]
 [76 68 40 29]]

[[73 72 39 78 77 91]
 [38 57 76 68 40 29]]


### seed it help generate the same random number 

In [29]:
np.random.seed(145)
arr=np.random.randint(0,100,12)
print(arr)

[37 86 87 18 90 69  8 53 33 32 40 26]


In [35]:
np.random.seed(111)
arr=np.random.randint(1,500,30).reshape(6,5)
print(type(arr))
print()
print(arr[2:,2:])
print()
print(arr[3:5,2:4])

<class 'numpy.ndarray'>

[[442   8 269]
 [369 217 285]
 [ 22  55 201]
 [231 187 269]]

[[369 217]
 [ 22  55]]


In [39]:
import numpy as np
ar=np.array([1,20,5,9,3,4,8,5,6,2,25,2,22,65,3,33])
slicing=ar[4:9]
print("new slicing:",slicing)
print("new array",ar)
print(type(slicing))
print(type(ar))
slicing[:]=0
print("old slicing",slicing)
print("old array",ar)

new slicing: [3 4 8 5 6]
new array [ 1 20  5  9  3  4  8  5  6  2 25  2 22 65  3 33]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
old slicing [0 0 0 0 0]
old array [ 1 20  5  9  0  0  0  0  0  2 25  2 22 65  3 33]


## arange( ,)it help generate sequence of number

In [49]:
ar=np.arange(1,15)
print(ar)
print(ar[ar%2!=0])
print(ar[ar%2==0])
print(ar[ar>8])
ar[ar%2==0]=0
print(ar)
ar=np.arange(1,15)
print(ar+2)
print(ar*2)
print(ar**2)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  3  5  7  9 11 13]
[ 2  4  6  8 10 12 14]
[ 9 10 11 12 13 14]
[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[  1   4   9  16  25  36  49  64  81 100 121 144 169 196]


In [50]:
ar=np.array([1,20,5,9,3,4,8,5,6,2,25,2,22,65,3,33])
print(np.min(ar))
print(np.max(ar))
print(np.argmin(ar))
print(np.argmax(ar))
print(np.sqrt(ar))
print(np.sin(ar))
print(np.cos(ar))

1
65
0
13
[1.         4.47213595 2.23606798 3.         1.73205081 2.
 2.82842712 2.23606798 2.44948974 1.41421356 5.         1.41421356
 4.69041576 8.06225775 1.73205081 5.74456265]
[ 0.84147098  0.91294525 -0.95892427  0.41211849  0.14112001 -0.7568025
  0.98935825 -0.95892427 -0.2794155   0.90929743 -0.13235175  0.90929743
 -0.00885131  0.82682868  0.14112001  0.99991186]
[ 0.54030231  0.40808206  0.28366219 -0.91113026 -0.9899925  -0.65364362
 -0.14550003  0.28366219  0.96017029 -0.41614684  0.99120281 -0.41614684
 -0.99996083 -0.56245385 -0.9899925  -0.01327675]


axis=0 colmun
axis=1 row

In [53]:
np.random.seed(122)
mat=np.random.randint(1,21,9).reshape(3,3)
print(mat)
print(np.sum(mat))
print(np.cumsum(mat))
print(np.min(mat))
print(np.max(mat))
print("--------------------")
print(np.sum(mat,axis=1))
print()
print(np.cumsum(mat,axis=1))
print()
print(np.min(mat,axis=1))
print()
print(np.max(mat,axis=1))
print("--------------------")
print(np.sum(mat,axis=0))
print()
print(np.cumsum(mat,axis=0))
print()
print(np.min(mat,axis=0))
print()
print(np.max(mat,axis=0))


[[16 11 13]
 [17 13 16]
 [ 3 16 11]]
116
[ 16  27  40  57  70  86  89 105 116]
3
17
--------------------
[40 46 30]

[[16 27 40]
 [17 30 46]
 [ 3 19 30]]

[11 13  3]

[16 17 16]
--------------------
[36 40 40]

[[16 11 13]
 [33 24 29]
 [36 40 40]]

[ 3 11 11]

[17 16 16]


In [54]:
np.random.seed(122)
mat=np.random.randint(1,21,10)
print(mat)
print()
np.random.shuffle(mat)
print(mat)
print()
print(np.unique(mat,return_index=True,return_counts=True))
print()
print(np.unique(mat).size)

[16 11 13 17 13 16  3 16 11 10]

[13 16 16 11 16 10 11 13 17  3]

(array([ 3, 10, 11, 13, 16, 17]), array([9, 5, 3, 0, 1, 8], dtype=int64), array([1, 1, 2, 2, 3, 1], dtype=int64))

6
