In [2]:
import numpy as np
mylist=[1,2,3,4,5]
a=np.array(mylist)
print(a)
print(type(a))


[1 2 3 4 5]
<class 'numpy.ndarray'>


convert the below list into a numpy array then display the array then display the fisrt and last index and multiply each elelment by 2

In [3]:
mylist=[1,2,3,4,5]
a=np.array(mylist)
print(a)
print(type(a))
print("multiply each elelment by :",a*2)
print("fisrt element:",a[0])
print("last element:",a[len(a)-1])

[1 2 3 4 5]
<class 'numpy.ndarray'>
multiply each elelment by : [ 2  4  6  8 10]
fisrt element: 1
last element: 5


write numpy program to create an array of 10 zeros , 10 ones , 10 fives.

In [4]:
a=np.zeros((10))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
a=np.ones((10))
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
a=np.ones((10))*5
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


write a umpy program to create  a 3x3 matix with values ranging from 2 to 10

In [7]:
ar=np.arange(2,11)
print(ar)
a=ar.reshape(3,3)
print(a)

[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [8]:
a=np.random.randint(2,10,size=(3,3))
print(a)

[[9 8 6]
 [3 9 7]
 [7 2 8]]
