1. Suppose you have a dataset containing daily temperature readings for a city, and you
want to identify days with extreme temperature conditions. Find days where the
temperature either exceeded 35 degrees Celsius (hot day) or dropped below 5 degrees
Celsius (cold day).
Input:
temperatures = np.array([32.5, 34.2, 36.8, 29.3, 31.0, 38.7, 23.1, 18.5, 22.8, 37.2])

In [2]:
import numpy as np
temperatures=np.array([32.5,34.2,36.8,29.3,31.0,38.7,23.1,18.5,22.8,37.2])
index=np.array(np.where(temperatures>35))
print(index)
t=(temperatures[temperatures>35])

print(t)


[[2 5 9]]
[36.8 38.7 37.2]


In [3]:
temperatures = np.array([32.5, 34.2, 36.8, 29.3, 31.0, 38.7, 23.1, 18.5, 22.8, 37.2, 4.0, -4.0, -12.0])

hot_days_indices = np.where(temperatures > 35)[0]
cold_days_indices = np.where(temperatures < 5)[0]

print("Hot Days:")
print("Day  Temperature (°C)")
for day in hot_days_indices:
    print(day+1,    temperatures[day])

print("\nCold Days:")
print("Day  Temperature (°C)")
for day in cold_days_indices:
    print(day+1,   temperatures[day])

Hot Days:
Day  Temperature (°C)
3 36.8
6 38.7
10 37.2

Cold Days:
Day  Temperature (°C)
11 4.0
12 -4.0
13 -12.0


2. Suppose you have a dataset containing monthly sales data for a company, and you
want to split this data into quarterly reports for analysis and reporting purposes.
Input:
monthly_sales = np.array([120, 135, 148, 165, 180, 155, 168, 190, 205, 198, 210, 225])

In [4]:

monthly_sales = np.array([120, 135, 148, 165, 180, 155, 168, 190, 205, 198, 210, 225])

quarterly_sales = monthly_sales.reshape(4, 3)

print("Quarter 1 Sales (in thousands of dollars):")
print(quarterly_sales[0])
print("\nQuarter 2 Sales (in thousands of dollars):")
print(quarterly_sales[1])
print("\nQuarter 3 Sales (in thousands of dollars):")
print(quarterly_sales[2])
print("\nQuarter 4 Sales (in thousands of dollars):")
print(quarterly_sales[3])


Quarter 1 Sales (in thousands of dollars):
[120 135 148]

Quarter 2 Sales (in thousands of dollars):
[165 180 155]

Quarter 3 Sales (in thousands of dollars):
[168 190 205]

Quarter 4 Sales (in thousands of dollars):
[198 210 225]


3. Suppose you have a dataset containing customer data, and you want to split this data
into two groups: one group for customers who made a purchase in the last 30 days and
another group for customers who haven't made a purchase in the last 30 days.
Input:
customer_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
last_purchase_days_ago = np.array([5, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [5]:
customer_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
last_purchase = np.array([5, 15, 20, 25, 30, 35, 40, 45, 50, 55])

new=np.array([])
ne2=np.array([])
i=0
while i<len(last_purchase):
    if last_purchase[i]>30:
        new=np.append(new,customer_ids[i])
    else:
        ne2=np.append(ne2,customer_ids[i])
    i+=1
print("active customer")
print(ne2)
print("inactive customer")
print(new)

active customer
[101. 102. 103. 104. 105.]
inactive customer
[106. 107. 108. 109. 110.]


4.Suppose you have two sets of employee data—one containing information about
full-time employees and another containing information about part-time employees. You
want to combine this data to create a comprehensive employee dataset for HR analysis.
Input:
Employee data for full-time employees
full_time_employees = np.array([
[101, 'John Doe', 'Full-Time', 55000],
[102, 'Jane Smith', 'Full-Time', 60000],
[103, 'Mike Johnson', 'Full-Time', 52000]
])
Employee data for part-time employees
part_time_employees = np.array([
[201, 'Alice Brown', 'Part-Time', 25000],
[202, 'Bob Wilson', 'Part-Time', 28000],
[203, 'Emily Davis', 'Part-Time', 22000]
])

In [6]:
full_time_employees = np.array([
[101, 'John Doe', 'Full-Time', 55000],
[102, 'Jane Smith', 'Full-Time', 60000],
[103, 'Mike Johnson', 'Full-Time', 52000]
])

part_time_employees = np.array([
[201, 'Alice Brown', 'Part-Time', 25000],
[202, 'Bob Wilson', 'Part-Time', 28000],
[203, 'Emily Davis', 'Part-Time', 22000]
])
all_employees = np.concatenate((full_time_employees, part_time_employees))

print("Comprehensive Employee Dataset:")
print(all_employees)

Comprehensive Employee Dataset:
[['101' 'John Doe' 'Full-Time' '55000']
 ['102' 'Jane Smith' 'Full-Time' '60000']
 ['103' 'Mike Johnson' 'Full-Time' '52000']
 ['201' 'Alice Brown' 'Part-Time' '25000']
 ['202' 'Bob Wilson' 'Part-Time' '28000']
 ['203' 'Emily Davis' 'Part-Time' '22000']]


1. How to find the mean of every NumPy array in the given list?
Input:
list = [
np.array([3, 2, 8, 9]),
np.array([4, 12, 34, 25, 78]),
np.array([23, 12, 67])
]

In [13]:
lists = [
np.array([3, 2, 8, 9]),
np.array([4, 12, 34, 25, 78]),
np.array([23, 12, 67])
]

means = [np.mean(arr) for arr in lists]
print("Mean of Each array:", means)

Mean of Each array: [5.5, 30.6, 34.0]


2. Compute the median of the flattened NumPy array
Input: x_odd = np.array([1, 2, 3, 4, 5, 6, 7])

In [15]:
x_odd = np.array([1, 2, 3, 4, 5, 6, 7])
print(x_odd)
medians=np.median(x_odd)
print(medians)

[1 2 3 4 5 6 7]
4.0


3. Compute the standard deviation of the NumPy array
Input: arr = [20, 2, 7, 1, 34]

In [16]:
arr = [20, 2, 7, 1, 34]
std_arr=np.std(arr)
print("standard deviation:",std_arr)


standard deviation: 12.576167937809991


4.Suppose you have a CSV file named 'house_prices.csv' with price information, and
you want to perform the following operations:
●
1.Read the data from the CSV file into a NumPy array.
●
2.Calculate the average of house prices.
●
3.Identify house price above the average.
●
4.Save the list of high prices to a new CSV file.