1. Convert the below list into numpy array then display the array 

Input: my_list = [1, 2, 3, 4, 5] 

In [2]:
import numpy as np
mylist=[1,2,3,4,5]
a=np.array(mylist)
print(a)
print(type(a))


[1 2 3 4 5]
<class 'numpy.ndarray'>


 2. Convert the below list into a numpy array then display the array then display the first and last index and then multiply each element by 2 and display the result. 

Input: my_list = [1, 2, 3, 4, 5] 

In [3]:
mylist=[1,2,3,4,5]
a=np.array(mylist)
print(a)
print(type(a))
print("multiply each elelment by :",a*2)
print("fisrt element:",a[0])
print("last element:",a[len(a)-1])

[1 2 3 4 5]
<class 'numpy.ndarray'>
multiply each elelment by : [ 2  4  6  8 10]
fisrt element: 1
last element: 5


1. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.  

In [4]:
a=np.zeros((10))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
a=np.ones((10))
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
a=np.ones((10))*5
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


 2. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. 

In [7]:
ar=np.arange(2,11)
print(ar)
a=ar.reshape(3,3)
print(a)

[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [8]:
a=np.random.randint(2,10,size=(3,3))
print(a)

[[7 6 4]
 [4 8 6]
 [5 7 7]]
